# @package _group_
cls_string: "LambdaSFQAgent"
kwargs:
  gamma: 0.9
  lamb: 0.0
  eta_trace: 0.0
  lr: 0.1
  reward_lr: null
  sf_lr: null
  policy_epsilon: 0.3
  use_lambda_q_control: False
  optim_kwargs:
    smoothing_alpha: 0.99