# @package _group_
cls_string: 'AsynchBatchedOfflineRunner'
kwargs:
  train_every_n_frames: 1  # default: 1
  train_iterations: 1  # default: 1
  batch_size: null
  replay_start_buffer_size: 5000  # default: 5000
buffer_kwargs:
  buffer_size: 100000  # default: 100,000
  batch_size: 32  # default: 32
